### ISSUE TITLE
Default platform config to UTF-8

### ISSUE THREAD

**Issue by monowai** [anapsix/docker-alpine-java#11]
The image appears to use US-ASCII as it's default encoding. Is there a flag to change it to UTF-8?

http://stackoverflow.com/questions/35517148/alpine-linux-gb18030-support

**Comment by anapsix** [comment]
I suspect it has to do with buggy glibc.
I guess I gotta upgrade to 2.23

**Comment by anapsix** [comment]
I've pushed an update, see if it helps.
If not - reopen

**Comment by monowai** [comment]
Works - thanks
