### ISSUE TITLE
Can not connect to github-cloud.s3.amazonaws.com

### ISSUE THREAD

**Issue by bujilvxing** [anapsix/docker-alpine-java#14]
[root@localhost jdk]# sudo docker build -t="xiaoyao/java" .
Sending build context to Docker daemon 4.608 kB
Step 1 : FROM alpine:3.4
Trying to pull repository docker.io/library/alpine ... 3.4: Pulling from library/alpine
5f05d2ba9e65: Pull complete 
Digest: sha256:7d7d68e60bec044b1821208884a2a4c9de64dfd5807f04cd32ffa5f5232d7848
Status: Downloaded newer image for docker.io/alpine:3.4

 ---> 5f05d2ba9e65
Step 2 : MAINTAINER Anastas Dancha anapsix@random.io
 ---> Running in 05576ff8959e
 ---> ea999e8c5c40
Removing intermediate container 05576ff8959e
Step 3 : ENV JAVA_VERSION_MAJOR 8 JAVA_VERSION_MINOR 92 JAVA_VERSION_BUILD 14 JAVA_PACKAGE jdk JAVA_HOME /opt/jdk PATH ${PATH}:/opt/jdk/bin LANG C.UTF-8
 ---> Running in 1e71c42099c3
 ---> bba26e54b1c3
Removing intermediate container 1e71c42099c3
Step 4 : RUN apk upgrade --update &&     apk add --update curl ca-certificates bash &&     for pkg in glibc-2.23-r1 glibc-bin-2.23-r1 glibc-i18n-2.23-r1; do curl -sSL https://github.com/andyshinn/alpine-pkg-glibc/releases/download/2.23-r1/${pkg}.apk -o /tmp/${pkg}.apk; done &&     apk add --allow-untrusted /tmp/_.apk &&     rm -v /tmp/_.apk &&     ( /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8 || true ) &&     echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh &&     /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib &&     mkdir /opt && curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" -o /tmp/java.tar.gz     http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/${JAVA_PACKAGE}-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.tar.gz &&     gunzip /tmp/java.tar.gz &&     tar -C /opt -xf /tmp/java.tar &&     apk del curl glibc-i18n &&     ln -s /opt/jdk1.${JAVA_VERSION_MAJOR}.0_${JAVA_VERSION_MINOR} /opt/jdk &&     rm -rf /opt/jdk/_src.zip            /opt/jdk/lib/missioncontrol            /opt/jdk/lib/visualvm            /opt/jdk/lib/_javafx\*            /opt/jdk/jre/plugin            /opt/jdk/jre/bin/javaws            /opt/jdk/jre/bin/jjs            /opt/jdk/jre/bin/keytool            /opt/jdk/jre/bin/orbd            /opt/jdk/jre/bin/pack200            /opt/jdk/jre/bin/policytool            /opt/jdk/jre/bin/rmid            /opt/jdk/jre/bin/rmiregistry            /opt/jdk/jre/bin/servertool            /opt/jdk/jre/bin/tnameserv            /opt/jdk/jre/bin/unpack200            /opt/jdk/jre/lib/javaws.jar            /opt/jdk/jre/lib/deploy\*            /opt/jdk/jre/lib/desktop            /opt/jdk/jre/lib/_javafx_            /opt/jdk/jre/lib/_jfx_            /opt/jdk/jre/lib/amd64/libdecora_sse.so            /opt/jdk/jre/lib/amd64/libprism__.so            /opt/jdk/jre/lib/amd64/libfxplugins.so            /opt/jdk/jre/lib/amd64/libglass.so            /opt/jdk/jre/lib/amd64/libgstreamer-lite.so            /opt/jdk/jre/lib/amd64/libjavafx_.so            /opt/jdk/jre/lib/amd64/libjfx_.so            /opt/jdk/jre/lib/ext/jfxrt.jar            /opt/jdk/jre/lib/ext/nashorn.jar            /opt/jdk/jre/lib/oblique-fonts            /opt/jdk/jre/lib/plugin.jar            /tmp/_ /var/cache/apk/\* &&     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf
 ---> Running in 52d4da7ffb1f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
OK: 5 MiB in 11 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/9) Installing ncurses-terminfo-base (6.0-r7)
(2/9) Installing ncurses-terminfo (6.0-r7)
(3/9) Installing ncurses-libs (6.0-r7)
(4/9) Installing readline (6.3.008-r4)
(5/9) Installing bash (4.3.42-r3)
Executing bash-4.3.42-r3.post-install
(6/9) Installing ca-certificates (20160104-r4)
(7/9) Installing libssh2 (1.7.0-r0)
(8/9) Installing libcurl (7.49.1-r0)
(9/9) Installing curl (7.49.1-r0)
Executing busybox-1.24.2-r8.trigger
Executing ca-certificates-20160104-r4.trigger
OK: 14 MiB in 20 packages
curl: (7) Failed to connect to github-cloud.s3.amazonaws.com port 443: Operation timed out

**Comment by ghost** [comment]
curl: (7) Failed to connect to github-cloud.s3.amazonaws.com port 443: Operation timed out
curl: (7) Failed to connect to github-cloud.s3.amazonaws.com port 443: Operation timed out
curl: (35) Unknown SSL protocol error in connection to github-cloud.s3.amazonaws.com:443 
The command '/bin/sh -c apk upgrade --update &&     apk add --update curl ca-certificates bash &&     for pkg in glibc-2.23-r1 glibc-bin-2.23-r1 glibc-i18n-2.23-r1; do curl -sSL https://github.com/andyshinn/alpine-pkg-glibc/releases/download/2.23-r1/${pkg}.apk -o /tmp/${pkg}.apk; done &&     apk add --allow-untrusted /tmp/_.apk &&     rm -v /tmp/_.apk &&     ( /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8 || true ) &&     echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh &&     /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib &&     mkdir /opt && curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" -o /tmp/java.tar.gz     http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/${JAVA_PACKAGE}-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.tar.gz &&     gunzip /tmp/java.tar.gz &&     tar -C /opt -xf /tmp/java.tar &&     apk del curl glibc-i18n &&     ln -s /opt/jdk1.${JAVA_VERSION_MAJOR}.0_${JAVA_VERSION_MINOR} /opt/jdk &&     rm -rf /opt/jdk/_src.zip            /opt/jdk/lib/missioncontrol            /opt/jdk/lib/visualvm            /opt/jdk/lib/_javafx\*            /opt/jdk/jre/plugin            /opt/jdk/jre/bin/javaws            /opt/jdk/jre/bin/jjs            /opt/jdk/jre/bin/keytool            /opt/jdk/jre/bin/orbd            /opt/jdk/jre/bin/pack200            /opt/jdk/jre/bin/policytool            /opt/jdk/jre/bin/rmid            /opt/jdk/jre/bin/rmiregistry            /opt/jdk/jre/bin/servertool            /opt/jdk/jre/bin/tnameserv            /opt/jdk/jre/bin/unpack200            /opt/jdk/jre/lib/javaws.jar            /opt/jdk/jre/lib/deploy\*            /opt/jdk/jre/lib/desktop            /opt/jdk/jre/lib/_javafx_            /opt/jdk/jre/lib/_jfx_            /opt/jdk/jre/lib/amd64/libdecora_sse.so            /opt/jdk/jre/lib/amd64/libprism__.so            /opt/jdk/jre/lib/amd64/libfxplugins.so            /opt/jdk/jre/lib/amd64/libglass.so            /opt/jdk/jre/lib/amd64/libgstreamer-lite.so            /opt/jdk/jre/lib/amd64/libjavafx_.so            /opt/jdk/jre/lib/amd64/libjfx_.so            /opt/jdk/jre/lib/ext/jfxrt.jar            /opt/jdk/jre/lib/ext/nashorn.jar            /opt/jdk/jre/lib/oblique-fonts            /opt/jdk/jre/lib/plugin.jar            /tmp/_ /var/cache/apk/\* &&     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf' returned a non-zero code: 35

**Comment by anapsix** [comment]
seems like Github was having some issues.. 
the glibc packages are there: https://github.com/sgerrand/alpine-pkg-glibc/releases
