### ISSUE TITLE
Add libstdc++

### ISSUE THREAD

**Issue by yarosman** [anapsix/docker-alpine-java#16]
Hello, can you add for you base image libstdc++.
 apk add --update libstdc++
Because in some cases it is required and without it throws exception:
UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni64-1.8 in java.library.path, no leveldbjni-1.8 in java.library.path, no leveldbjni in java.library.path, /tmp/libleveldbjni-64: libstdc++.so.6: cannot open shared obj.

**Comment by anapsix** [comment]
thanks, added libstdc++
