### ISSUE TITLE
More precise tags

### ISSUE THREAD

**Issue by smaant** [anapsix/docker-alpine-java#17]
Hello. Is it possible to do more precise version-tags?
Our project has dependency on ALPN which is very tightly coupled to a specific version of JVM so we need to make sure our JVM won't be updated accidentally. We could do this if you added separate tag for each JVM version, similar to https://hub.docker.com/_/java/

**Comment by anapsix** [comment]
added new style tagging, for example:
`8u102b14_jdk`
`8u92b14_jdk`

New version will be added using above pattern

**Comment by smaant** [comment]
Awesome, thank you for such a quick reaction!
