### ISSUE TITLE
Consider not removing keytool

### ISSUE THREAD

**Issue by praseodym** [anapsix/docker-alpine-java#22]
To support an internal CA, we need to add a certificate to the JVM trust store. The easiest solution would be add a `CMD` that imports the certificate into `/opt/jdk/jre/lib/security/cacerts` using `keytool`. Unfortunately, `keytool` is stripped from the image. Please consider not removing it; the tool is just 7.8K in size, so not removing it is not a big deal in terms of image size.

**Comment by kuhnroyal** [comment]
You would be more flexible mounting the keystore into the container and create it someplace else.

**Comment by praseodym** [comment]
I also considered `ADD`ing a new keystore myself, but I think adding an entire new truststore is less transparent than just adding a single CA certificate.

**Comment by nateww** [comment]
I agree with the original author.  We use environment variables for all configuration (we reference a base64 encoded certificate as an environment variable), and the lack of keystore is an issue.

https://12factor.net/

I created the following PR:

https://github.com/anapsix/docker-alpine-java/pull/23

**Comment by anapsix** [comment]
Merged
