### ISSUE TITLE
wrong user ids?

### ISSUE THREAD

**Issue by Daxten** [anapsix/docker-alpine-java#28]
Hey,
on my Host system daemon has the userid 1, in this container daemon is userid 2 and bin userid 1
when using

$ docker run -v /hostfolder:/data docker-alpine-java:8

/data will be owned by bin and not by daemon

I THINK daemon should always be userid 1, or is this something I will have to change on my end? (other containers work fine)

**Comment by anapsix** [comment]
weird..
I'm not able to replicate it
```
root@do:~# mkdir /tmp/test
root@do:~# cd /tmp/test
root@do:/tmp/test# docker run -it --rm -v $(pwd):/opt anapsix/alpine-java bash -c 'whoami > /opt/hello'
root@do:/tmp/test# ls -la hello
-rw-r--r-- 1 root root 5 Jan 17 13:40 hello
root@do:/tmp/test# stat hello
  File: ‘hello’
  Size: 5         	Blocks: 8          IO Block: 4096   regular file
Device: fe01h/65025d	Inode: 32645       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-01-17 13:40:26.780000000 -0500
Modify: 2017-01-17 13:40:16.964000000 -0500
Change: 2017-01-17 13:40:16.964000000 -0500
 Birth: -
root@do:/tmp/test# cat hello
root
```
perhaps, you are running it via entrypoint, that is spawning whatever additional process creating file?

**Comment by Daxten** [comment]
hey, this is not my specialty so maybe I'm interpretting this wrong. Let me paste some stuff:

```
$ cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
...
$  docker run anapsix/alpine-java cat /etc/passwd
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
$ mkdir test
$ sudo chown daemon:daemon test
$ ls -lk
total 4
drwxr-xr-x 2 daemon daemon 4096 Jan 18 15:30 test
$ docker run -v ~/test:/data/test anapsix/alpine-java ls -lk /data
total 4
drwxr-xr-x    2 bin      bin           4096 Jan 18 14:30 test
```

**Comment by anapsix** [comment]
when creating files outside of container, the UIDs of your host system most likely will not match UIDs inside of your container, especially when your host and container are based on different distos.
