### ISSUE TITLE
nashorn class not found

### ISSUE THREAD

**Issue by kiwiwin** [anapsix/docker-alpine-java#36]
when i run with base image anapsix/alpine-java:8

i got the error
java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/NashornScriptEngineFactory

any idea about which image tag should i use?

**Comment by anapsix** [comment]
@kiwiwin Nashorn Script Engine is explicitly removed from this image.
You could build your own images based on this one, without removing Nashorn (see [line 69](https://github.com/anapsix/docker-alpine-java/blob/master/Dockerfile.server-jre.tpl#L69) of `Dockerfile.server-jre.tpl`) or use official java image

**Comment by anapsix** [comment]
https://github.com/anapsix/docker-alpine-java/pull/60#issuecomment-443534560
