### ISSUE TITLE
Docker removes extensions. In particular opt/jdk/jre/lib/ext/nashorn.jar. 

### ISSUE THREAD

**Issue by VDema** [anapsix/docker-alpine-java#42]
No problem but what should i do if i need this one extension in my docker container?
I couldn't find this library in any repository: maven or jcenter.

**Comment by anapsix** [comment]
Since Nashorn Script Engine is explicitly removed from this image, you could build your own images based on this one, yet without removing Nashorn (see line 69 of Dockerfile.server-jre.tpl) or use official java image
