### ISSUE TITLE
JVM without nashorn

### ISSUE THREAD

**Issue by belimawr** [anapsix/docker-alpine-java#45]
Why did you remove Nashorn from the image?

You could add a image version with nashorn or with the full JVM, I know that the image will be bigger, however some people may need those extra features.

**Comment by anapsix** [comment]
See #42

**Comment by belimawr** [comment]
Thanks,

I already build my own image with Nashorn, however is there any reason to do not have an image option with the full JVM?

**Comment by anapsix** [comment]
The image was created as "minified"..
I suppose I could also add a series of tags with full size JVM
