### ISSUE TITLE
Add checksum verification of oracle jdks

### ISSUE THREAD

**Issue by landro** [anapsix/docker-alpine-java#49]
The image build is vulnerable to MITM attacks on the installed jdk during the build (curl -k switch etc).
Wouldn't it make sense to add a sha256 checksum verification by adding something like 

    echo "62b215bdfb48bace523723cdbb2157c665e6a25429c73828a32f00e587301236  /tmp/java.tar.gz" > /tmp/java.tar.gz.sha256.txt && \
    sha256sum -c /tmp/java.tar.gz.sha256.txt && \

before gunzipping the jdk download?

Oracle checksums can be found at https://www.oracle.com/webfolder/s/digest/8u131checksum.html and similar

**Comment by anapsix** [comment]
Good suggestion, will do. Thanks

**Comment by anapsix** [comment]
done

**Comment by 2manyvcos** [comment]
This doesn't work for 7u80b15.
There are only MD5 checksums on the [checksum page](https://www.oracle.com/webfolder/s/digest/7u80checksum.html)...

Looks like Java 7 ist not available for download on the Oracle website anymore.

**Comment by anapsix** [comment]
@hatsuo, since Oracle does not publish the Java 7 packages no more, it's moot
