### ISSUE TITLE
Consider not removing Nashorn or making it configurable

### ISSUE THREAD

**Issue by deinspanjer** [anapsix/docker-alpine-java#50]
We have been using this docker image for a while and were very happy with it, but we recently added some Nashorn scripting to our application, and we discovered that it doesn't work with this image so we will have to look at using something different.

**Comment by landro** [comment]
Have you tried adding nashorn to the application classpath manually and have the jdk pick it up using the service loader mechanism, @deinspanjer ?

**Comment by deinspanjer** [comment]
No I haven't.  If I understand correctly, you are suggesting to take the jar file from a JDK installation and either copy it into my application's classpath or manually move it into the container image and reference it?

I didn't want to get into a state where I was picking bits out of a JDK release and maintaining them myself, so I haven't looked at this approach.  For now, I just switched to use the plain official openjdk image as size is not a critical factor for this particular application.

**Comment by manikmagar** [comment]
Also, adding that jar back-in would duplicate the whole file size and thus increasing the actual file size of the image. I think it will be good to keep it in the initial setup. I too need it but I don't want to switch to openjdk as I want to keep the size small. I think I will fork this one, modify and use it, unless the original repo has this. Hope that is ok! Thanks for writing this awesome image!

**Comment by anapsix** [comment]
added `8_nashorn`,  `8_server-jre_nashorn`, and `8_jdk_nashorn` some time ago
see https://github.com/anapsix/docker-alpine-java/pull/60#issuecomment-445522550
