### ISSUE TITLE
Upgrade to Java 8u152

### ISSUE THREAD

**Issue by clehene** [anapsix/docker-alpine-java#53]
Note that there were some changes regarding the crypto policies
http://www.oracle.com/technetwork/java/javase/8u151-relnotes-3850493.html

>security-libs/javax.crypto
> New Security property to control crypto policy
>This release introduces a new feature whereby the JCE jurisdiction policy files used by the JDK can be controlled via a new Security property. In older releases, JCE jurisdiction files had to be downloaded and installed separately to allow unlimited cryptography to be used by the JDK. The download and install steps are no longer necessary. To enable unlimited cryptography, one can use the new crypto.policy Security property. If the new Security property (crypto.policy) is set in the java.security file, or has been set dynamically using the Security.setProperty() call before the JCE framework has been initialized, that setting will be honored. By default, the property will be undefined. If the property is undefined and the legacy JCE jurisdiction files don't exist in the legacy lib/security directory, then the default cryptographic level will remain at 'limited'. To configure the JDK to use unlimited cryptography, set the crypto.policy to a value of 'unlimited'. See the notes in the java.security file shipping with this release for more information.

**Comment by Sineaggi** [comment]
On line 826 of the `jre/lib/security/java.security` file you can uncomment the `#crypto.policy=unlimited` line to enable unlimited security.

**Comment by anapsix** [comment]
upgraded to 8u152b16
