### ISSUE TITLE
Docker build is failing, not able to download jdk 8u144b01 jar

### ISSUE THREAD

**Issue by jilanirails** [anapsix/docker-alpine-java#54]
Error:
invalid magic

Reason of failure: download for jdk 8u144b01 is failing
curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" -o /tmp/java.tar.gz \
      http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/090f390dda5b47b9b721c7dfaa008135/${JAVA_PACKAGE}-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.tar.gz && \
    gunzip /tmp/java.tar.gz && \

Docker file: https://github.com/anapsix/docker-alpine-java/blob/master/8/144b01/jdk/standard/Dockerfile

**Comment by skupfer** [comment]
```
+ /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8
LC_MONETARY: value of field `int_curr_symbol' has wrong length
No definition for LC_PAPER category found
No definition for LC_NAME category found
No definition for LC_ADDRESS category found
No definition for LC_TELEPHONE category found
No definition for LC_MEASUREMENT category found
No definition for LC_IDENTIFICATION category found
+ true
+ echo export LANG=C.UTF-8
+ /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib
+ mkdir /opt
+ curl -jksSLH Cookie: oraclelicense=accept-securebackup-cookie -o /tmp/java.tar.gz http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/server-jre-8u144-linux-x64.tar.gz
+ gunzip /tmp/java.tar.gz
gunzip: invalid magic
```

Can confirm. Here are the last lines

EDIT: for most recent use the following

```
JAVA_VERSION_MAJOR=8 \
JAVA_VERSION_MINOR=151 \
JAVA_VERSION_BUILD=12 \

curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" -o /tmp/java.tar.gz \
      http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/e758a0de34e24606bca991d704f6dcbf/${JAVA_PACKAGE}-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.tar.gz
```

works for server-jre and from a quick look seems to be the same for the jdk (e758a0de34e24606bca991d704f6dcbf)

**Comment by jilanirails** [comment]
Thanks Skupfer for quick response. 

Yes, I have faced the same last lines for 8u144b01 version error message 'invalid magic'.
Thanks, I will use latest version 8, 151, 12 version.

**Comment by anapsix** [comment]
8u152b16 is out, 8u144b01 have been fixed a while ago
