### ISSUE TITLE
8u162b12_jdk_unlimited tag isn't available

### ISSUE THREAD

**Issue by abdolence** [anapsix/docker-alpine-java#57]
Hello,

I noticed that 8u162b12_jdk_unlimited tag isn't available (8u152b16_jdk_unlimited is there) at https://hub.docker.com/r/anapsix/alpine-java/tags/.
Has something changed recently?

Thanks for your work,
Abdulla

**Comment by landro** [comment]
Have a look here: 
https://www.petefreitag.com/item/844.cfm

Sendt fra min iPhone

**Comment by abdolence** [comment]
Hmmm... It is about security, not absence a particular docker image at docker hub. How is it connected to this topic?

**Comment by landro** [comment]
Unlimited security, yeah?

Sendt fra min iPhone

**Comment by abdolence** [comment]
Ok, you must be confused with my "_unlimited" suffix. I meant there isn't any 8u162b12_**jdk** at all (limited/unlimited doesn't matter :) 
Only 8u162b12-server-**jre** available at https://hub.docker.com/r/anapsix/alpine-java/tags/.

**Comment by anapsix** [comment]
hmm. gotta re-push the tag

**Comment by anapsix** [comment]
just finished building.. available now
