### ISSUE TITLE
'Setting the timezone' support

### ISSUE THREAD

**Issue by barrer** [anapsix/docker-alpine-java#58]
Currently there seems no way to set the time zone, may need the support of the tzdata library.

[https://wiki.alpinelinux.org/wiki/Setting_the_timezone](https://wiki.alpinelinux.org/wiki/Setting_the_timezone)

[https://bugs.alpinelinux.org/issues/5543](https://bugs.alpinelinux.org/issues/5543)

[https://forums.docker.com/t/synchronize-timezone-from-host-to-container/39116](https://forums.docker.com/t/synchronize-timezone-from-host-to-container/39116)

**Comment by anapsix** [comment]
perhaps, those looking for this feature, could `apk add -U tzdata`?
or is this (missing "tzdata") something that breaks image's common usage pattern?

**Comment by barrer** [comment]
@anapsix 

host machine timezone: ```America/Los_Angeles```  
docker container timezone needs is: ```Asia/Shanghai```  

usage: ```-v /custom/timezone:/etc/timezone:ro -v /custom/localtime:/etc/localtime:ro -e TZ=Asia/Shanghai```   
for this image(**docker pull anapsix/alpine-java:8**) does not work, but centos, ubuntu is working

centos 7 `Dockerfile`
```
FROM centos:7

ENV JAVA_HOME=/custom/jdk1.8.0_144 \
	PATH=/custom/jdk1.8.0_144/bin:${PATH} \
	CLASSPATH=.:/custom/jdk1.8.0_144/lib/dt.jar:/custom/jdk1.8.0_144/lib/tools.jar

COPY jdk-8u144-linux-x64.tar.gz /

RUN mkdir -p /custom \
	&& tar -xzvf /jdk-8u144-linux-x64.tar.gz -C /custom \
	&& rm -f /jdk-8u144-linux-x64.tar.gz
```
`jdk-8u144-linux-x64.tar.gz` download from oracle.com

**Comment by barrer** [comment]
The original alpine(3.6) image is also working.  
Maybe some things broken the image environment?

`Dockerfile`
```
FROM alpine:3.6
```

```docker build -t my/test:1 .```
```docker run --rm --name test -v /custom/localtime:/etc/localtime:ro -it my/test:1```

'`/custom/localtime`' file you can find in linux '`/usr/share/zoneinfo/Asia/Shanghai`' directory.  

What's the difference between localtime and timezone files?  
[https://unix.stackexchange.com/a/384977](https://unix.stackexchange.com/a/384977)

**Comment by manikmagar** [comment]
This is what I did to get timezone in image using this as base image -

Add `apk add --update tzdata && \` [here](https://github.com/javastreets/docker-arena/blob/master/mule/Dockerfile#L19)
If TZ value is set from ENV, then add that to `/etc/timezone` like [this](https://github.com/javastreets/docker-arena/blob/master/mule/Dockerfile#L28) 

While running the container, you can pass-in TZ environment variable `-e TZ=Asia/Shanghai`.

This is working for me.

**Comment by Jazzepi** [comment]
@manikmagar That second link is broken. Got one that works?

**Comment by manikmagar** [comment]
@jazzepi here is the new link -   https://github.com/javastreets/mule-docker-image/blob/master/Dockerfile#L28
  

  
Looks like I renamed my repo later 🙂
  

  
  

  
  
>
