### ISSUE TITLE
Is it really 47MB ? 

### ISSUE THREAD

**Issue by greenlaw110** [anapsix/docker-alpine-java#68]
I tried anapsix/alpine-java:8 and anapsix/alpine-java:8_server-jre_unlimited, they all give me a large `127 MB` image:

```
anapsix/alpine-java                 8                           ff37138c2a5f        6 days ago          127 MB
anapsix/alpine-java                 8_server-jre_unlimited      d7fc5f14f358        6 days ago          127 MB
```

Wondering where is `47MB` come from

**Comment by anapsix** [comment]
Microbadger counts the compressed size, not size on disk
See https://github.com/microscaling/microbadger/issues/1
