### ISSUE TITLE
Java 10 support ?

### ISSUE THREAD

**Issue by sabareeshkkanan** [anapsix/docker-alpine-java#69]
Yes as Java 10 is already out do we have any plans for it ?

**Comment by anapsix** [comment]
pull requests are welcome

**Comment by kouky** [comment]
@anapsix I'd like to work on this. Not sure exactly how to go about it.

**Comment by anapsix** [comment]
@kouky, thank you for enthusiasm.
take a look at [`generate_dockerfiles.sh`](https://github.com/anapsix/docker-alpine-java/blob/master/generate_dockerfiles.sh). Java 10 has a different versioning format, for it would look like `10.0.2-13-19aef61b38124481863b1413dce1855f`. Changes to the script would need to be made to be able to deal with changed format.
You might need to add new template specifically for Java 10 JRE/JDK, as it might need to be customized in what extra libs can be removed to slim down the image, etc.
Perhaps refactor templates: one template per version (7 vs. 8 vs. 10), and not type (jre vs. jdk).

**Comment by anapsix** [comment]
this is unlikely to happen with current Oracle Java licensing terms (see #82)
