### ISSUE TITLE
Add 192b12

### ISSUE THREAD

**Issue by MPV** [anapsix/docker-alpine-java#75]
@anapsix Would you be up for adding Java version `192b12`?

It seems Oracle has now removed the older version I was using (Java `8.181.13`).

Kudos to @1zha0 for showing that it worked:
https://github.com/1zha0/docker-alpine-python-java/blob/master/8/192b12/jdk-dcevm/standard/Dockerfile

**Comment by anapsix** [comment]
upgraded to `8u192b12` and `alpine:3.8`
