### ISSUE TITLE
Unable to install maven in image

### ISSUE THREAD

**Issue by ghost** [anapsix/docker-alpine-java#76]
```
$ apk add maven
WARNING: This apk-tools is OLD! Some packages might not function properly.
ERROR: unsatisfiable constraints:
  maven (missing):
    required by: world[maven]
```
This is after apk update and upgrade.

**Comment by anapsix** [comment]
best way to install Maven is by 
- downloading it from https://maven.apache.org/download.cgi
- installing it as described in https://maven.apache.org/install.html
