### ISSUE TITLE
Suggestion: Don't remove curl

### ISSUE THREAD

**Issue by hho** [anapsix/docker-alpine-java#8]
The title pretty much says it all :-)

I get that you're trying to minimize image size, but `curl` is tiny and when using this image as a base for something else, you pretty much need curl anyway to add stuff (for example, downloading anything from Apache).

**Comment by anapsix** [comment]
In your case, could you use `wget`,  which part of busybox?

**Comment by hho** [comment]
Good idea, thanks.
It doesn't work with https though, while `curl` seems to use the installed `ca-certificates` package.

**Comment by anapsix** [comment]
@hho, I'd like to understand your use case better.. 
Do you use `curl` when building an image based on mine?
If so, `apk -U add curl` and `apk del curl` don't seem like that much of an overhead..
For some use cases, you could even use [Dockerfile `ADD` directive](https://docs.docker.com/engine/reference/builder/#add) to get remote file even without `curl` or `wget`.

Imho, if you often find needing `curl` while running things inside container, adding it to the image makes more sense..

**Comment by hho** [comment]
I've tried to set up Docker Swarm running Apache Samza. So I built images for Zookeeper, Kafka and Hadoop Yarn. As you correctly pointed out, `wget` works for the downloads as well, so I closed this issue.

**Comment by carek** [comment]
I would like to suggest leaving curl as well. I need it in healthcheck command.

**Comment by cosbor11** [comment]
I need curl to do docker healthchecks and even when I add it to the image I still get /bin/sh curl command not found;

**Comment by landro** [comment]
Have you tried wget?

**Comment by junneyang** [comment]
+1

**Comment by junneyang** [comment]
i need post/put/delete method
