### ISSUE TITLE
Can't checkout particular MAJOR-MINOR-BUILD

### ISSUE THREAD

**Issue by angheladrianclaudiu** [anapsix/docker-alpine-java#80]
I am trying the following commands:
```docker pull anapsix/alpine-java:8u202b08```
```docker pull anapsix/alpine-java:8u172b11```
and get the outputs:
```Error response from daemon: manifest for anapsix/alpine-java:8u202b08 not found```
```Error response from daemon: manifest for anapsix/alpine-java:8u172b11 not found```

What is the problem with these particular builds?

**Comment by anapsix** [comment]
you need to pick server-jre or jdk
```
docker pull anapsix/alpine-java:8u172b11_server-jre
docker pull anapsix/alpine-java:8u172b11_jdk
docker pull anapsix/alpine-java:8u202b08_jdk
docker pull anapsix/alpine-java:8u202b08_server-jre
```

**Comment by anapsix** [comment]
see available tags on Docker Hub
https://cloud.docker.com/repository/docker/anapsix/alpine-java/tags
